---
- hosts: localhost
  connection: local
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: update repos (arch)
      pacman: update_cache=yes
      changed_when: False
      when: {{ ansible_facts['os_family'] }} == "Archlinux"

    - name: update repos (debian)
      apt: update_cache=yes
      changed_when: False
      when: {{ ansible_facts['os_family'] }} == "Debian"

    - name: update repos (suse)
      zypper: update_cache=yes
      changed_when: False
      when: {{ ansible_facts['os_family'] }} == "Suse"

  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
