---
- name: Clone my dotfiles repo
  become_user: jackson
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    force: yes

- name: Check if all the dotfiles are links
  become_user: jackson
  command: "ls -F {{ home_path }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  check_mode: false
  changed_when: false
  with_items: "{{ dotfiles }}"

- name: Move to backup for dotfiles file that are not links
  become_user: jackson
  command: "mv {{ home_path }}/{{ dotfiles[item.0] }} {{ home_path }}/{{ dotfiles[item.0] }}.bak"
  when: "'@' not in item.1.stdout and item.1.stdout != ''"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Link dotfiles into home folder
  become_user: jackson
  file:
    src: "{{ dotfiles_repo_local_destination }}/{{ item }}"
    dest: "{{ home_path }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles }}"

- name: Setting up vim plugins
  become_user: jackson
  command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
